### PR TITLE
Add initial support for extension operations in ePoxy server

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change adds support for ePoxy extensions. Currently the extension operations are hard-coded. Ultimately this configuration should be stored in Datastore alongside host records and other configuration.

As well, this change modifies the app.yaml configuration for the epoxy server by placing it on a VPC network named "epoxy-extension-private-network" (we can pick an alternate name). Other GCE VMs hosting extension services should define an interface in this network at creation time so that the ePoxy server can connect to it.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/epoxy/41)

### CODE REVIEW

**Comment by gfr10598** [comment]
FYI, I think I'm a little confused by the term Webhook.  I generally interpret this to mean an optional, independent, registered event that happens when some triggering event happens.  But I think it also has implicit in it that the client that caused the original event does not depend on the Webhook event happening - that client doesn't generally know anything about the Webhook(s).

It seems like here, the Webhooks are providing services that the client is making explicit use of.  So I like the "extension" and "proxy" terminology, but the webhook terminology leads me astray into confusion.

As I read the rest of the code, I'll see if any useful suggestions emerge.

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/epoxy/41#-:-LCjnO-r7nvh9vNtoJgF:b7rkme0)*

**Comment by gfr10598** [comment]
A few more questions.  Code itself looks pretty good otherwise.

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---

*[extension/webhook.go, line 28 at r2](https://reviewable.io/reviews/m-lab/epoxy/41#-LCjo_pl-_yi__6_31KV:-LCjo_pl-_yi__6_31KW:b-sa7ql) ([raw file](https://github.com/m-lab/epoxy/blob/db1300a30f7a4e20c53cc0b99f83e49f7ecbb715/extension/webhook.go#L28)):*
> ```Go
> 
> // WebhookRequest contains information about a booting machine
> type WebhookRequest struct {
> ```

maybe ProxyRequest?  Or ExtensionRequest?

---

*[handler/handler.go, line 197 at r2](https://reviewable.io/reviews/m-lab/epoxy/41#-LCjvOwA7uCE9KQejqT0:-LCjvOwA7uCE9KQejqT1:brtfp9u) ([raw file](https://github.com/m-lab/epoxy/blob/db1300a30f7a4e20c53cc0b99f83e49f7ecbb715/handler/handler.go#L197)):*
> ```Go
> 	sessionID := mux.Vars(req)["sessionID"]
> 	// TODO: support multiple extensions.
> 	if sessionID != host.CurrentSessionIDs.ExtensionID {
> ```

Is it necessary to have a separate ExtensionID?  Can a single session ID be used for all requests?

---

*[handler/handler.go, line 202 at r2](https://reviewable.io/reviews/m-lab/epoxy/41#-LCjw1En7euPsxPd6wbf:-LCjw1En7euPsxPd6wbg:b-6xbbj5) ([raw file](https://github.com/m-lab/epoxy/blob/db1300a30f7a4e20c53cc0b99f83e49f7ecbb715/handler/handler.go#L202)):*
> ```Go
> 	}
> 
> 	operation := mux.Vars(req)["operation"]
> ```

IIUC, operation is both encoded in the URL, and specified as a request param.  Am I misinterpreting?  Is the redundancy useful?

---

*[template/template_test.go, line 53 at r2](https://reviewable.io/reviews/m-lab/epoxy/41#-LCjxUxB2xX4-4XEA_iO:-LCjxUxB2xX4-4XEA_iP:bn23jjl) ([raw file](https://github.com/m-lab/epoxy/blob/db1300a30f7a4e20c53cc0b99f83e49f7ecbb715/template/template_test.go#L53)):*
> ```Go
> 			Stage3ID:    "56789",
> 			ReportID:    "86420",
> 			ExtensionID: "75319",
> ```

Is a particular extension associated with a particular stage?  Or are extensions available to all stages?

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/epoxy/41#-:-LCjxjxr2BwTP787qhWc:b-rez2nf)*

**Comment by stephen-soltesz** [comment]
I've responded to the open comments. I need to add some new text in main.go -- will do that in the morning.

---

Review status: 0 of 12 files reviewed at latest revision, 4 unresolved discussions.

---

*[handler/handler.go, line 197 at r2](https://reviewable.io/reviews/m-lab/epoxy/41#-LCjvOwA7uCE9KQejqT0:-LCkNIKnCYoyX9YCe76e:bxx7i0z) ([raw file](https://github.com/m-lab/epoxy/blob/db1300a30f7a4e20c53cc0b99f83e49f7ecbb715/handler/handler.go#L197)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Is it necessary to have a separate ExtensionID?  Can a single session ID be used for all requests?
</blockquote></details>

So, we discussed a little in person. The original thinking is that session IDs are single-use and are incrementally revoked as they are used to progress from one stage to the next or after successfully using an extension url. Not re-using session IDs for different operations is part of the security model for epoxy. Each URL becomes a unique "capability" for the operation.

---

*[handler/handler.go, line 202 at r2](https://reviewable.io/reviews/m-lab/epoxy/41#-LCjw1En7euPsxPd6wbf:-LCk1KZdDS9KWwnHlkau:bu26qbs) ([raw file](https://github.com/m-lab/epoxy/blob/db1300a30f7a4e20c53cc0b99f83e49f7ecbb715/handler/handler.go#L202)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

IIUC, operation is both encoded in the URL, and specified as a request param.  Am I misinterpreting?  Is the redundancy useful?
</blockquote></details>

This may be a misinterpretation of the syntax. In main.go we declare patterns that match specific components in the URL. For example, `/v1/boot/{hostname}/{sessionID}/extension/{operation}`. The "operation" read on this line equals the value that mux parsed from the `{operation}` field in the requested path. So, the only value used by the client is the URL path. There is no additional request param.

---

*[template/template_test.go, line 53 at r2](https://reviewable.io/reviews/m-lab/epoxy/41#-LCjxUxB2xX4-4XEA_iO:-LCkNoOS2xovTJa_ig4a:bdyda87) ([raw file](https://github.com/m-lab/epoxy/blob/db1300a30f7a4e20c53cc0b99f83e49f7ecbb715/template/template_test.go#L53)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Is a particular extension associated with a particular stage?  Or are extensions available to all stages?
</blockquote></details>

Good question. This is undecided. As currently imagined an extension is single-use and would not be tied to any particular stage. Our first use-case would use it in stage3. It's possible some future extensions could want to be used in both stage2 and stage3.

---

*[extension/webhook.go, line 28 at r2](https://reviewable.io/reviews/m-lab/epoxy/41#-LCjo_pl-_yi__6_31KV:-LCkMMVK6Vf8H-vUYnHG:b-2avcev) ([raw file](https://github.com/m-lab/epoxy/blob/db1300a30f7a4e20c53cc0b99f83e49f7ecbb715/extension/webhook.go#L28)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

maybe ProxyRequest?  Or ExtensionRequest?
</blockquote></details>

Ah, how about simply `extension.Request`? Also renamed file.

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/epoxy/41#-:-LCkTVHgCGmHfQCc_g8Z:b-c0juxu)*

**Comment by gfr10598** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/example_extension_server/main.go, line 46 at r3](https://reviewable.io/reviews/m-lab/epoxy/41#-LCnljHlEVy7vwSaQdXS:-LCnljHlEVy7vwSaQdXT:b5g5uzj) ([raw file](https://github.com/m-lab/epoxy/blob/fd3dd70f35e0235e980be79b2c31172522758f14/cmd/example_extension_server/main.go#L46)):*
> ```Go
> 	var result *returnMessage
> 
> 	// Decode the webhook request.
> ```

There are still a few references to webhook that need cleaning up.

---

*[handler/handler.go, line 184 at r3](https://reviewable.io/reviews/m-lab/epoxy/41#-LCnlyB3BIhtzdoXQlYh:-LCnlyB3BIhtzdoXQlYi:bta0hv9) ([raw file](https://github.com/m-lab/epoxy/blob/fd3dd70f35e0235e980be79b2c31172522758f14/handler/handler.go#L184)):*
> ```Go
> 
> // HandleExtension handles client requests to ePoxy extension URLs. The handler creates
> // and sends a webhook request to the extension service registered for the operation.
> ```

s/webhook// ?

---

*[handler/handler_test.go, line 323 at r3](https://reviewable.io/reviews/m-lab/epoxy/41#-LCnm1796vKavPCFy_Kr:-LCnm1796vKavPCFy_Ks:bta0hv9) ([raw file](https://github.com/m-lab/epoxy/blob/fd3dd70f35e0235e980be79b2c31172522758f14/handler/handler_test.go#L323)):*
> ```Go
> 		LastSessionCreation: time.Date(2018, 5, 1, 0, 0, 0, 0, time.UTC),
> 	}
> 	// The webhook request that should be received by the extension server.
> ```

s/webhook// ?

---

*[handler/handler_test.go, line 416 at r3](https://reviewable.io/reviews/m-lab/epoxy/41#-LCnm2dC24NQLTOSmRud:-LCnm2dC24NQLTOSmRue:bta0hv9) ([raw file](https://github.com/m-lab/epoxy/blob/fd3dd70f35e0235e980be79b2c31172522758f14/handler/handler_test.go#L416)):*
> ```Go
> 						tt.expectedRequest.V1.IPv4Address != ext.V1.IPv4Address ||
> 						tt.expectedRequest.V1.IPv6Address != ext.V1.IPv6Address {
> 						t.Errorf("HandleExtension() malformed webhook request: got %#v, want %#v",
> ```

s/webhook// ?

---

*[extension/request.go, line 16 at r3](https://reviewable.io/reviews/m-lab/epoxy/41#-LCnlqIU9ScMWs7UiGTC:-LCnlqIU9ScMWs7UiGTD:b-ecqqtm) ([raw file](https://github.com/m-lab/epoxy/blob/fd3dd70f35e0235e980be79b2c31172522758f14/extension/request.go#L16)):*
> ```Go
> //////////////////////////////////////////////////////////////////////////////
> 
> // Package extension defines the Extension Webhook API used between the ePoxy
> ```

s/Webhook//

---

*[extension/webhook.go, line 28 at r2](https://reviewable.io/reviews/m-lab/epoxy/41#-LCjo_pl-_yi__6_31KV:-LCnlVib0nZHMWTTxmMG:b-ec019s) ([raw file](https://github.com/m-lab/epoxy/blob/db1300a30f7a4e20c53cc0b99f83e49f7ecbb715/extension/webhook.go#L28)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Ah, how about simply `extension.Request`? Also renamed file.
</blockquote></details>

Excellent!

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/epoxy/41)*

**Comment by gfr10598** [comment]
:lgtm:

---

Review status: 0 of 12 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/epoxy/41#-:-LCnm9FC46Maq_qtnAZE:bnfp4nl)*

**Comment by stephen-soltesz** [comment]
Thank you!

---

Review status: 0 of 12 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[cmd/example_extension_server/main.go, line 46 at r3](https://reviewable.io/reviews/m-lab/epoxy/41#-LCnljHlEVy7vwSaQdXS:-LCnsrNk9vP9FIgahjRg:b-896fix) ([raw file](https://github.com/m-lab/epoxy/blob/fd3dd70f35e0235e980be79b2c31172522758f14/cmd/example_extension_server/main.go#L46)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

There are still a few references to webhook that need cleaning up.
</blockquote></details>

Done.

---

*[handler/handler.go, line 184 at r3](https://reviewable.io/reviews/m-lab/epoxy/41#-LCnlyB3BIhtzdoXQlYh:-LCnswBb5lZfNmJe-Qbm:b-896fix) ([raw file](https://github.com/m-lab/epoxy/blob/fd3dd70f35e0235e980be79b2c31172522758f14/handler/handler.go#L184)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

s/webhook// ?
</blockquote></details>

Done.

---

*[handler/handler_test.go, line 323 at r3](https://reviewable.io/reviews/m-lab/epoxy/41#-LCnm1796vKavPCFy_Kr:-LCnswxE-iGc3RDrsCt-:b-896fix) ([raw file](https://github.com/m-lab/epoxy/blob/fd3dd70f35e0235e980be79b2c31172522758f14/handler/handler_test.go#L323)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

s/webhook// ?
</blockquote></details>

Done.

---

*[handler/handler_test.go, line 416 at r3](https://reviewable.io/reviews/m-lab/epoxy/41#-LCnm2dC24NQLTOSmRud:-LCnsxSj4HJ_PYMp--G_:b-896fix) ([raw file](https://github.com/m-lab/epoxy/blob/fd3dd70f35e0235e980be79b2c31172522758f14/handler/handler_test.go#L416)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

s/webhook// ?
</blockquote></details>

Done.

---

*[extension/request.go, line 16 at r3](https://reviewable.io/reviews/m-lab/epoxy/41#-LCnlqIU9ScMWs7UiGTC:-LCnstTl1F4nNiZfP3fw:b-896fix) ([raw file](https://github.com/m-lab/epoxy/blob/fd3dd70f35e0235e980be79b2c31172522758f14/extension/request.go#L16)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

s/Webhook//
</blockquote></details>

Done.

---

*[extension/webhook.go, line 28 at r2](https://reviewable.io/reviews/m-lab/epoxy/41#-LCjo_pl-_yi__6_31KV:-LCnsuJu-SNAQeMjVJQd:b-896fix) ([raw file](https://github.com/m-lab/epoxy/blob/db1300a30f7a4e20c53cc0b99f83e49f7ecbb715/extension/webhook.go#L28)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Excellent!
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/epoxy/41#-:-LCnt-TZ1io7Oc3XQHRS:b-9755fn)*

**Pull request merged**
