### PR TITLE
Add a minimal epoxy boot server with automated sandbox and staging deployment

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This PR adds a minimal epoxy boot server as well as a mechanism to automate the sandbox and staging deployment process to AppEngine.

The Go code was previously reviewed. This PR makes that code public and adds travis integration.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/epoxy/2)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Reviewed 2 of 8 files at r1.
Review status: 2 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/epoxy/2)*

**Comment by gfr10598** [comment]
Review status: 2 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[.travis.yml, line 1 at r2](https://reviewable.io:443/reviews/m-lab/epoxy/2#-K_f5o4Ib5GV8dMu9S7Z:-K_f5o4JRob1DbkEza0z:b-urx0) ([raw file](https://github.com/m-lab/epoxy/blob/264537b61283179a92318bdc9b6313d2f3b06023/.travis.yml#L1)):*
> ```YAML
> language: go
> ```

What would you think about starting the practice of including a header comment with an outline of functionality provided by the file?

---

*[.travis.yml, line 4 at r2](https://reviewable.io:443/reviews/m-lab/epoxy/2#-K_f4n6Mwgh4r_dwUXZw:-K_f4n6Mwgh4r_dwUXZx:b9ga1ta) ([raw file](https://github.com/m-lab/epoxy/blob/264537b61283179a92318bdc9b6313d2f3b06023/.travis.yml#L4)):*
> ```YAML
> 
> before_install:
> # Encrypted values are not defined in forks or pull requests.
> ```

Add description of what is expected, the output generated, and what it is used for.

---

*[.travis.yml, line 23 at r2](https://reviewable.io:443/reviews/m-lab/epoxy/2#-K_eLyX4NVVjj0yguL1H:-K_eLyX4NVVjj0yguL1I:b-cuafx0) ([raw file](https://github.com/m-lab/epoxy/blob/264537b61283179a92318bdc9b6313d2f3b06023/.travis.yml#L23)):*
> ```YAML
> - $TRAVIS_BUILD_DIR/travis/install_gcloud.sh
> 
> # NB: travis has a "gae" provider, however it does not work here (unknown).
> ```

has a Google App Engine provider, "gae" , ...

---

*[.travis.yml, line 26 at r2](https://reviewable.io:443/reviews/m-lab/epoxy/2#-K_eMgFUNv5uTqzn0-C3:-K_eMgFUNv5uTqzn0-C4:byr8fhg) ([raw file](https://github.com/m-lab/epoxy/blob/264537b61283179a92318bdc9b6313d2f3b06023/.travis.yml#L26)):*
> ```YAML
> # Deploy steps never trigger on a new Pull Request. Deploy steps will trigger
> # after a merge with matching "on:" conditions.
> deploy:
> ```

How about reversing the order, so that the deployments generally proceed downward?

---

*[.travis.yml, line 29 at r2](https://reviewable.io:443/reviews/m-lab/epoxy/2#-K_eMWixWlu495cnHUzJ:-K_eMWiyXJB_3y5WVYvb:bhyw1k9) ([raw file](https://github.com/m-lab/epoxy/blob/264537b61283179a92318bdc9b6313d2f3b06023/.travis.yml#L29)):*
>   - provider: script
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>
>     script: /bin/true
>     skip_cleanup: true
>     on:
>       repo: m-lab/epoxy
>       branch: master
</details>
Delete this code and just leave the TODO.

---

*[travis/deploy_app.sh, line 3 at r2](https://reviewable.io:443/reviews/m-lab/epoxy/2#-K_f6akhrj1e550YlAeV:-K_f6akhrj1e550YlAeW:bkpxrle) ([raw file](https://github.com/m-lab/epoxy/blob/264537b61283179a92318bdc9b6313d2f3b06023/travis/deploy_app.sh#L3)):*
> ```Shell
> #!/bin/bash
> #
> # Performs an AppEngine deployment using service account credentials.
> ```

Add links to https://cloud.google.com/sdk/gcloud/reference/app/deploy and https://cloud.google.com/sdk/gcloud/reference/config/ ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/epoxy/2)*

**Comment by stephen-soltesz** [comment]
Review status: 2 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[.travis.yml, line 1 at r2](https://reviewable.io:443/reviews/m-lab/epoxy/2#-K_f5o4Ib5GV8dMu9S7Z:-K_fsMT4nyLzurwYACLw:b-mjhd01) ([raw file](https://github.com/m-lab/epoxy/blob/264537b61283179a92318bdc9b6313d2f3b06023/.travis.yml#L1)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

What would you think about starting the practice of including a header comment with an outline of functionality provided by the file?
</blockquote></details>

That sounds like a really good idea. The travis directives are a little cryptic by themselves. A high-level summary is helpful.

---

*[.travis.yml, line 4 at r2](https://reviewable.io:443/reviews/m-lab/epoxy/2#-K_f4n6Mwgh4r_dwUXZw:-K_fuXfu_s_F2-a0smBK:b2xs79w) ([raw file](https://github.com/m-lab/epoxy/blob/264537b61283179a92318bdc9b6313d2f3b06023/.travis.yml#L4)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Add description of what is expected, the output generated, and what it is used for.
</blockquote></details>

How's it look?

---

*[.travis.yml, line 23 at r2](https://reviewable.io:443/reviews/m-lab/epoxy/2#-K_eLyX4NVVjj0yguL1H:-K_fDYaahqmf7GuLJDCc:b-896fix) ([raw file](https://github.com/m-lab/epoxy/blob/264537b61283179a92318bdc9b6313d2f3b06023/.travis.yml#L23)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

has a Google App Engine provider, "gae" , ...
</blockquote></details>

Done.

---

*[.travis.yml, line 26 at r2](https://reviewable.io:443/reviews/m-lab/epoxy/2#-K_eMgFUNv5uTqzn0-C3:-K_fDWIj-tLKQNTCym8C:bbr3dvq) ([raw file](https://github.com/m-lab/epoxy/blob/264537b61283179a92318bdc9b6313d2f3b06023/.travis.yml#L26)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

How about reversing the order, so that the deployments generally proceed downward?
</blockquote></details>

Sounds good. Done.

---

*[.travis.yml, line 29 at r2](https://reviewable.io:443/reviews/m-lab/epoxy/2#-K_eMWixWlu495cnHUzJ:-K_fDVPBsgsuWgM6rXyP:b-896fix) ([raw file](https://github.com/m-lab/epoxy/blob/264537b61283179a92318bdc9b6313d2f3b06023/.travis.yml#L29)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

>   - provider: script
>     script: /bin/true
>     skip_cleanup: true
>     on:
>       repo: m-lab/epoxy
>       branch: master
Delete this code and just leave the TODO.
</blockquote></details>

Done.

---

*[travis/deploy_app.sh, line 3 at r2](https://reviewable.io:443/reviews/m-lab/epoxy/2#-K_f6akhrj1e550YlAeV:-K_fvSddZaU9XLLzqZiK:b-f7yt6n) ([raw file](https://github.com/m-lab/epoxy/blob/264537b61283179a92318bdc9b6313d2f3b06023/travis/deploy_app.sh#L3)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Add links to https://cloud.google.com/sdk/gcloud/reference/app/deploy and https://cloud.google.com/sdk/gcloud/reference/config/ ?
</blockquote></details>

Done. Added in context.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/epoxy/2)*

**Comment by gfr10598** [comment]
:lgtm:

---

Review status: 2 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[.travis.yml, line 1 at r2](https://reviewable.io:443/reviews/m-lab/epoxy/2#-K_f5o4Ib5GV8dMu9S7Z:-Kah_kKrRuGYF9wtMYHX:bnl88m8) ([raw file](https://github.com/m-lab/epoxy/blob/264537b61283179a92318bdc9b6313d2f3b06023/.travis.yml#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

That sounds like a really good idea. The travis directives are a little cryptic by themselves. A high-level summary is helpful.
</blockquote></details>

Nice.  LGTM

---

*[.travis.yml, line 4 at r2](https://reviewable.io:443/reviews/m-lab/epoxy/2#-K_f4n6Mwgh4r_dwUXZw:-Kahbyw6tlRBwB7MgaQT:bb6ywmx) ([raw file](https://github.com/m-lab/epoxy/blob/264537b61283179a92318bdc9b6313d2f3b06023/.travis.yml#L4)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

How's it look?
</blockquote></details>

LGTM

---

*[.travis.yml, line 29 at r2](https://reviewable.io:443/reviews/m-lab/epoxy/2#-K_eMWixWlu495cnHUzJ:-KahbYaO9lS2sKYyJ-Qf:bb6ywmx) ([raw file](https://github.com/m-lab/epoxy/blob/264537b61283179a92318bdc9b6313d2f3b06023/.travis.yml#L29)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

LGTM

---

*[.travis.yml, line 31 at r3](https://reviewable.io:443/reviews/m-lab/epoxy/2#-KahaeUyIuiVS43_9g4P:-KahaeUyIuiVS43_9g4Q:b-ku4atk) ([raw file](https://github.com/m-lab/epoxy/blob/0859cdd7436117feece531b2006d11b1e1849102/.travis.yml#L31)):*
> ```YAML
>   tar -C /tmp -xvf /tmp/service-accounts.tar ; fi
> 
> # NB: The cache is created (if needed) after the "script" build completes, and
> ```

Why "if needed"?  Not sure this really needs a comment, but maybe something like "These directories will be cached on successful builds, and restored, if available, to save time on future builds." 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/epoxy/2#-:-Kahc2iQLzM6L00d0e7T:bnfp4nl)*

**Comment by stephen-soltesz** [comment]
Thank you!

---

Review status: 2 of 8 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[.travis.yml, line 31 at r3](https://reviewable.io:443/reviews/m-lab/epoxy/2#-KahaeUyIuiVS43_9g4P:-KahxEEUY15kddjI6BBj:b-abhxbw) ([raw file](https://github.com/m-lab/epoxy/blob/0859cdd7436117feece531b2006d11b1e1849102/.travis.yml#L31)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Why "if needed"?  Not sure this really needs a comment, but maybe something like "These directories will be cached on successful builds, and restored, if available, to save time on future builds." 
</blockquote></details>

Here, I really wanted to make it clear that the "cache" configuration applied to directories created during the "script" actions. I wish travis had named the "script" section "build" instead.

I used your suggested text with a slight change to call out "script" explicitly again.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/epoxy/2#-:-KahyrFfWBWMgROjeM9Z:b-9755fn)*

**Pull request merged**
