### PR TITLE
 Run commands with evaluation of Vars, Env, and Commands

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change begins to implement support for running Commands.

In particular, this changes supports evaluation of Vars from Kargs, Env from Vars and Kargs, and Commands from Vars and Kargs. Support for Files will be added in a later change.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/epoxy/14)

### CODE REVIEW

**Comment by gfr10598** [comment]
Quick high level comments:

From a quick skim, it looks like quite a lot is going here.  I gather an understanding of the template library would help, but I don't really have that yet.

I think it would be worthwhile adding a medium size header describing at a fairly high level how this is intended to be used.  Maybe suitable to put some of that content into README as well, or instead with references here to the README.

---

Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[nextboot/v1.go, line 196 at r1](https://reviewable.io:443/reviews/m-lab/epoxy/14#-L41lGa-1W2g0c2pHX7R:-L41lGa-1W2g0c2pHX7S:bqq4y9g) ([raw file](https://github.com/m-lab/epoxy/blob/5838d4ed8ca47f85ce595fbfac8bad70c237d6a1/nextboot/v1.go#L196)):*
> ```Go
> }
> 
> // evaluateCommands normalies the underlying Commands types, converting
> ```

normalies?

---

*[nextboot/v1.go, line 198 at r1](https://reviewable.io:443/reviews/m-lab/epoxy/14#-L41l7EKBNYUt3oH7Atj:-L41l7EKBNYUt3oH7Atk:bcqf3kj) ([raw file](https://github.com/m-lab/epoxy/blob/5838d4ed8ca47f85ce595fbfac8bad70c237d6a1/nextboot/v1.go#L198)):*
> ```Go
> // evaluateCommands normalies the underlying Commands types, converting
> // every element to []string.
> func (c *Config) evaluateCommands() error {
> ```

Nit:  Some languages use evaluate to mean execute.  Would "parse" be a suitable alternative?

I see it is also doing substitution, so perhaps evaluate is better.

---

*[nextboot/v1.go, line 257 at r1](https://reviewable.io:443/reviews/m-lab/epoxy/14#-L41llOFK7xpCcua08TI:-L41llOFK7xpCcua08TJ:b-qdecs) ([raw file](https://github.com/m-lab/epoxy/blob/5838d4ed8ca47f85ce595fbfac8bad70c237d6a1/nextboot/v1.go#L257)):*
> ```Go
> 	return s
> }
> ```

Could you add a comment for this func?

---

*[nextboot/v1.go, line 258 at r1](https://reviewable.io:443/reviews/m-lab/epoxy/14#-L41kCsSLyObIYD-kQeH:-L41kCsThTJePbSPJjtn:b2kqd2m) ([raw file](https://github.com/m-lab/epoxy/blob/5838d4ed8ca47f85ce595fbfac8bad70c237d6a1/nextboot/v1.go#L258)):*
> ```Go
> }
> 
> func (c *Config) evaluateAsTemplate(value string, flags int) (string, error) {
> ```

FYI: Should we be thinking of using struct of bools for this kind of flags use?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/epoxy/14#-:-L41mhA5hK8d-VltTpZ-:bjdusrk)*

**Comment by stephen-soltesz** [comment]
I agree that we'll want more documentation. Right now the best reference is the docstrings on the nextboot.Config type and the corresponding example config. A more conversational walk through of the example in the form of a README sounds like a good idea.

https://github.com/m-lab/epoxy/blob/dev/nextboot/nextboot.go
https://github.com/m-lab/epoxy/blob/dev/nextboot/example.json

---

Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/epoxy/14#-:-L41pt4ScqG3oBnd1BEY:b-j7iqor)*

**Comment by gfr10598** [comment]
Review status: 0 of 2 files reviewed at latest revision, 10 unresolved discussions.

---

*[nextboot/v1.go, line 29 at r1](https://reviewable.io:443/reviews/m-lab/epoxy/14#-L41yxE3ZQdzaRIi7kTV:-L41yxE4VSBOVsskMuZj:b-j8viuf) ([raw file](https://github.com/m-lab/epoxy/blob/5838d4ed8ca47f85ce595fbfac8bad70c237d6a1/nextboot/v1.go#L29)):*
> ```Go
> // useVars and useFiles are flags for evaluating templates.
> const (
> 	useVars int = 1 << iota
> ```

evalVars, evalFiles ?

---

*[nextboot/v1.go, line 122 at r1](https://reviewable.io:443/reviews/m-lab/epoxy/14#-L424oyGpBwKD9-ciOfF:-L424oyGpBwKD9-ciOfG:b8qu7nb) ([raw file](https://github.com/m-lab/epoxy/blob/5838d4ed8ca47f85ce595fbfac8bad70c237d6a1/nextboot/v1.go#L122)):*
> ```Go
> 
> 	for _, fields := range c.V1.Commands {
> 		// Convert the native Commands []interface{} type to []string.
> ```

BTW: Is using []interface{} adding any value?  I assume some usecase requires this, but if not, could simplify the code quite a bit.

---

*[nextboot/v1.go, line 148 at r1](https://reviewable.io:443/reviews/m-lab/epoxy/14#-L41zYlMVtsMm8MHLXGp:-L41zYlMVtsMm8MHLXGq:b-2j833o) ([raw file](https://github.com/m-lab/epoxy/blob/5838d4ed8ca47f85ce595fbfac8bad70c237d6a1/nextboot/v1.go#L148)):*
> ```Go
> }
> 
> func updateCurrentEnv(env map[string]string) map[string]string {
> ```

Maybe note that this does not provide for unsetting env vars that were absent before.
Or alternatively handle that, using LookupEnv?

---

*[nextboot/v1.go, line 163 at r1](https://reviewable.io:443/reviews/m-lab/epoxy/14#-L42-DRrbK0JLpyqVSVb:-L42-DRrbK0JLpyqVSVc:b-xf4bfg) ([raw file](https://github.com/m-lab/epoxy/blob/5838d4ed8ca47f85ce595fbfac8bad70c237d6a1/nextboot/v1.go#L163)):*
> ```Go
> 		case []interface{}:
> 			// Reconstruct a single string from an array of strings.
> 			c.V1.Vars[key] = strings.Join(interfaceToStringArray(val), " ")
> ```

Should this be (value, " ") ?

---

*[nextboot/v1.go, line 167 at r1](https://reviewable.io:443/reviews/m-lab/epoxy/14#-L42-pxINQ_WmkOsH5Bg:-L42-pxINQ_WmkOsH5Bh:bm4kezs) ([raw file](https://github.com/m-lab/epoxy/blob/5838d4ed8ca47f85ce595fbfac8bad70c237d6a1/nextboot/v1.go#L167)):*
> ```Go
> 			// No-op, this is good as-is.
> 		default:
> 			return fmt.Errorf("Unsupported type: %T %#v", val, val)
> ```

Vars docstring says that other types are ignored.  But this is terminating the eval.

---

*[nextboot/v1.go, line 182 at r1](https://reviewable.io:443/reviews/m-lab/epoxy/14#-L4208hnG_tbIoi2yDYH:-L4208hnG_tbIoi2yDYI:b-ihe8w0) ([raw file](https://github.com/m-lab/epoxy/blob/5838d4ed8ca47f85ce595fbfac8bad70c237d6a1/nextboot/v1.go#L182)):*
> ```Go
> func (c *Config) evaluateFiles() error {
> 	// TODO: implement large file download.
> 	return nil
> ```

Do you want to return an error until you implement this?

---

*[nextboot/v1.go, line 258 at r1](https://reviewable.io:443/reviews/m-lab/epoxy/14#-L41kCsSLyObIYD-kQeH:-L420s2BwGNx0jQwBIbT:b-ygleeh) ([raw file](https://github.com/m-lab/epoxy/blob/5838d4ed8ca47f85ce595fbfac8bad70c237d6a1/nextboot/v1.go#L258)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

FYI: Should we be thinking of using struct of bools for this kind of flags use?
</blockquote></details>

Bit vectors should be unsigned.  (Hmm - wonder where that assertion originates)

---

*[nextboot/v1.go, line 272 at r1](https://reviewable.io:443/reviews/m-lab/epoxy/14#-L420mLMjd9vFcR-88Yr:-L420mLMjd9vFcR-88Ys:b32uwx) ([raw file](https://github.com/m-lab/epoxy/blob/5838d4ed8ca47f85ce595fbfac8bad70c237d6a1/nextboot/v1.go#L272)):*
> ```Go
> 	// Allocate an empty namespace map, and conditionally set vars and files.
> 	ns := map[string]interface{}{}
> 	if flags&useVars > 0 {
> ```

!=

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/epoxy/14)*

**Comment by stephen-soltesz** [comment]
PTAL?

---

Review status: 0 of 2 files reviewed at latest revision, 10 unresolved discussions.

---

*[nextboot/v1.go, line 29 at r1](https://reviewable.io:443/reviews/m-lab/epoxy/14#-L41yxE3ZQdzaRIi7kTV:-L42T4SPIsM1aFFEWhdW:bwqin5) ([raw file](https://github.com/m-lab/epoxy/blob/5838d4ed8ca47f85ce595fbfac8bad70c237d6a1/nextboot/v1.go#L29)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

evalVars, evalFiles ?
</blockquote></details>

These flags are meant to indicate whether particular elements of the V1 struct are available when evaluating templates. I could imagine alternatively to `useVars`, `withVars` or `includeVars`. 

The names `evalVars` initially sounded like a misnomer to me.

---

*[nextboot/v1.go, line 122 at r1](https://reviewable.io:443/reviews/m-lab/epoxy/14#-L424oyGpBwKD9-ciOfF:-L42TpQyAx9OCUNBff48:b-ykot92) ([raw file](https://github.com/m-lab/epoxy/blob/5838d4ed8ca47f85ce595fbfac8bad70c237d6a1/nextboot/v1.go#L122)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

BTW: Is using []interface{} adding any value?  I assume some usecase requires this, but if not, could simplify the code quite a bit.
</blockquote></details>

My thought is that there is a trade-off between making the user interface (config) more complex or the code more complex.

The `[]interface{}` is a consequence of the JSON unmarshal process. While the JSON text may be an "array of strings", the unmarshal creates an "array of interface{}". This makes sense to me after the fact, since JSON has no restrictions on types in an array, and it would be more difficult to check whether all elements are of the same type.

Additionally, we want to support commands that are "all one string" (for simplicity) as well as "array of args" (for a fallbback or clearer formatting).

Since I imagine the user side of creating and managing these configs as they feed into the system, I was willing to pay for simplicity on the "UI" side at the expense of some code complexity.

Are there other strategies that might be helpful?

---

*[nextboot/v1.go, line 148 at r1](https://reviewable.io:443/reviews/m-lab/epoxy/14#-L41zYlMVtsMm8MHLXGp:-L42Ws1kge7Tbd4lplGo:b-trmnl4) ([raw file](https://github.com/m-lab/epoxy/blob/5838d4ed8ca47f85ce595fbfac8bad70c237d6a1/nextboot/v1.go#L148)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Maybe note that this does not provide for unsetting env vars that were absent before.
Or alternatively handle that, using LookupEnv?
</blockquote></details>

Yes, I was being a little lazy. I've updated the implementation to backup the original values and whether they were present.

---

*[nextboot/v1.go, line 163 at r1](https://reviewable.io:443/reviews/m-lab/epoxy/14#-L42-DRrbK0JLpyqVSVb:-L42WwM9EwpekEYd9CPd:bb9nava) ([raw file](https://github.com/m-lab/epoxy/blob/5838d4ed8ca47f85ce595fbfac8bad70c237d6a1/nextboot/v1.go#L163)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Should this be (value, " ") ?
</blockquote></details>

In a type switch `val` takes on the type of the `case` statement. Otherwise, the usage of `value` here would require another type assertion.

---

*[nextboot/v1.go, line 167 at r1](https://reviewable.io:443/reviews/m-lab/epoxy/14#-L42-pxINQ_WmkOsH5Bg:-L42XLS9H9S1oZbGiMur:b-6a5gcp) ([raw file](https://github.com/m-lab/epoxy/blob/5838d4ed8ca47f85ce595fbfac8bad70c237d6a1/nextboot/v1.go#L167)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Vars docstring says that other types are ignored.  But this is terminating the eval.
</blockquote></details>

Excellent careful reading of the notes! I knew that I was creating an inconsistency. But, I hadn't made up my mind about which I wanted to do yet. Added a TODO to decide.

---

*[nextboot/v1.go, line 182 at r1](https://reviewable.io:443/reviews/m-lab/epoxy/14#-L4208hnG_tbIoi2yDYH:-L42bUcuqi4ImOdM9URC:b-2p08b7) ([raw file](https://github.com/m-lab/epoxy/blob/5838d4ed8ca47f85ce595fbfac8bad70c237d6a1/nextboot/v1.go#L182)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Do you want to return an error until you implement this?
</blockquote></details>

The implementation is in the next PR. And, if this errored, I couldn't test partial configs as easily. I guess I could have made this conditional on the presence of `c.V1.Files`. But, I have the code already it's just too much for one PR.

---

*[nextboot/v1.go, line 196 at r1](https://reviewable.io:443/reviews/m-lab/epoxy/14#-L41lGa-1W2g0c2pHX7R:-L42cm9JV2_uBpOeUbsJ:b-aktaju) ([raw file](https://github.com/m-lab/epoxy/blob/5838d4ed8ca47f85ce595fbfac8bad70c237d6a1/nextboot/v1.go#L196)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

normalies?
</blockquote></details>

normalizes :) Fixed.

---

*[nextboot/v1.go, line 257 at r1](https://reviewable.io:443/reviews/m-lab/epoxy/14#-L41llOFK7xpCcua08TI:-L42dug0K03MTNoUsVVc:b-896fix) ([raw file](https://github.com/m-lab/epoxy/blob/5838d4ed8ca47f85ce595fbfac8bad70c237d6a1/nextboot/v1.go#L257)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Could you add a comment for this func?
</blockquote></details>

Done.

---

*[nextboot/v1.go, line 258 at r1](https://reviewable.io:443/reviews/m-lab/epoxy/14#-L41kCsSLyObIYD-kQeH:-L42e9KRo0Lw5-6u3Uuy:b-se6rb0) ([raw file](https://github.com/m-lab/epoxy/blob/5838d4ed8ca47f85ce595fbfac8bad70c237d6a1/nextboot/v1.go#L258)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Bit vectors should be unsigned.  (Hmm - wonder where that assertion originates)
</blockquote></details>

Done.

A struct may be better if this were part of a public interface.

---

*[nextboot/v1.go, line 272 at r1](https://reviewable.io:443/reviews/m-lab/epoxy/14#-L420mLMjd9vFcR-88Yr:-L42eI-vwMKwykanhlJ1:b-896fix) ([raw file](https://github.com/m-lab/epoxy/blob/5838d4ed8ca47f85ce595fbfac8bad70c237d6a1/nextboot/v1.go#L272)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

!=
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/epoxy/14#-:-L43-cxTDcbOE0JSDT_r:b-833305)*

**Comment by gfr10598** [comment]
:lgtm:
One question about correctness, but assume you will ensure it is correct.

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[nextboot/v1.go, line 122 at r1](https://reviewable.io:443/reviews/m-lab/epoxy/14#-L424oyGpBwKD9-ciOfF:-L43BwCJ37Kd_12LGkal:b-svy2gk) ([raw file](https://github.com/m-lab/epoxy/blob/5838d4ed8ca47f85ce595fbfac8bad70c237d6a1/nextboot/v1.go#L122)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

My thought is that there is a trade-off between making the user interface (config) more complex or the code more complex.

The `[]interface{}` is a consequence of the JSON unmarshal process. While the JSON text may be an "array of strings", the unmarshal creates an "array of interface{}". This makes sense to me after the fact, since JSON has no restrictions on types in an array, and it would be more difficult to check whether all elements are of the same type.

Additionally, we want to support commands that are "all one string" (for simplicity) as well as "array of args" (for a fallbback or clearer formatting).

Since I imagine the user side of creating and managing these configs as they feed into the system, I was willing to pay for simplicity on the "UI" side at the expense of some code complexity.

Are there other strategies that might be helpful?
</blockquote></details>

The json consequence is compelling.  No good alternate strategy comes to mind.

---

*[nextboot/v1.go, line 163 at r1](https://reviewable.io:443/reviews/m-lab/epoxy/14#-L42-DRrbK0JLpyqVSVb:-L43EO-rlzN-gSksG0HL:b-hs5wde) ([raw file](https://github.com/m-lab/epoxy/blob/5838d4ed8ca47f85ce595fbfac8bad70c237d6a1/nextboot/v1.go#L163)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

In a type switch `val` takes on the type of the `case` statement. Otherwise, the usage of `value` here would require another type assertion.
</blockquote></details>

D'oh.  Sorry.

---

*[nextboot/v1.go, line 164 at r2](https://reviewable.io:443/reviews/m-lab/epoxy/14#-L43CY-1helCMqVps3HR:-L43CY-1helCMqVps3HS:b-fo64bq) ([raw file](https://github.com/m-lab/epoxy/blob/f7b21c0b9438794968ecb7b709202e5445f8ad81/nextboot/v1.go#L164)):*
> ```Go
> 		os.Setenv(key, val)
> 		// If the key is present in delenv, and was previously not found, unset it.
> 		if found, ok := delenv[key]; ok && !found {
> ```

Hmm - doesn't seem quite right.
I think you want to start by deleting all items in delenv.
Then do all the updates, saving anything new to "added" and existing to "changed"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/epoxy/14#-:-L43EkyguT8Keg0d_yTc:bth71as)*

**Comment by stephen-soltesz** [comment]
Thank you for the review and suggested improvements!

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[nextboot/v1.go, line 164 at r2](https://reviewable.io:443/reviews/m-lab/epoxy/14#-L43CY-1helCMqVps3HR:-L43Fg5kLmKq30xGqiMm:b-76m1md) ([raw file](https://github.com/m-lab/epoxy/blob/f7b21c0b9438794968ecb7b709202e5445f8ad81/nextboot/v1.go#L164)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Hmm - doesn't seem quite right.
I think you want to start by deleting all items in delenv.
Then do all the updates, saving anything new to "added" and existing to "changed"

</blockquote></details>

Your suggestion is easier to reason about. In particular just tracking the two sets as literally "changed" or "added" makes a lot of sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/epoxy/14#-:-L43T-WX-I3izMqJAQJv:byn7h4)*

**Pull request merged**
